# Generated by Django 5.0.6 on 2024-06-15 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(1, 'Superadmin'), (2, 'Moderator'), (3, 'Contentcreator')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionID', models.IntegerField(primary_key=1, serialize=False)),
                ('nameUG', models.CharField(max_length=30)),
                ('descriptionUG', models.CharField(max_length=450)),
                ('publicUG', models.BooleanField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontImg', models.ImageField(upload_to='moneyPhotos/front/')),
                ('backImg', models.ImageField(upload_to='moneyPhotos/back/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'create'), ('EDIT', 'edit'), ('DELETE', 'delete'), ('BAN', 'ban'), ('UNBAN', 'unban')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('USER', 'user'), ('POST', 'post')], max_length=10)),
                ('notesUG', models.TextField(blank=1, null=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderationLogs', to='coinSocial.admin')),
            ],
        ),
    ]
