# Generated by Django 5.0.6 on 2024-06-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(1, 'Superadmin'), (2, 'Moderator'), (3, 'Contentcreator')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUG', models.CharField(max_length=30)),
                ('descriptionUG', models.CharField(max_length=450)),
                ('publicUG', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNameUG', models.CharField(max_length=15)),
                ('profilePicUG', models.ImageField(null=1, upload_to='profilePic/')),
                ('userType', models.BooleanField(default=0)),
                ('descriptionUG', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=1)),
                ('value', models.IntegerField(default=0, null=1)),
                ('condition', models.CharField(choices=[('MINT', 'mint'), ('GOOD', 'good'), ('NORMAL', 'normal'), ('POOR', 'poor')], default='Normal', max_length=10)),
                ('origin', models.CharField(max_length=30, null=1)),
                ('description', models.TextField(blank=1, null=1)),
                ('dateOfIssue', models.DateTimeField(default='Unknown', verbose_name='date of Issue')),
                ('frontImg', models.ImageField(upload_to='moneyPhotos/front/')),
                ('backImg', models.ImageField(upload_to='moneyPhotos/back/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'create'), ('EDIT', 'edit'), ('DELETE', 'delete'), ('BAN', 'ban'), ('UNBAN', 'unban')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('USER', 'user'), ('POST', 'post')], max_length=10)),
                ('notesUG', models.TextField(blank=1, null=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderationLogs', to='coinSocial.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('editedTime', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.user')),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.user')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.user'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinSocial.user'),
        ),
    ]
