# Generated by Django 5.0.6 on 2024-06-19 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinSocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='user',
            field=models.OneToOneField(null=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
