# Generated by Django 5.0.6 on 2024-06-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinSocial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='descriptionUG',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='nameUG',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='publicUG',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='moderationlog',
            old_name='notesUG',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='descriptionUG',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profilePicUG',
            new_name='profilePic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userNameUG',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.IntegerField(choices=[(3, 'Superadmin'), (2, 'Moderator'), (1, 'Contentcreator')], default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateOfIssue',
            field=models.DateTimeField(blank=1, null=1, verbose_name='date of Issue'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
